name: Deploy homepage with SSH

on:
  workflow_run:
    branches: [invalid]
    workflows: [CodeQL]
    types:
      - completed


permissions:
  contents: read

jobs:
  build-and-deploy:
    name: Build and deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout project
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Install pnpm
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          version: 8.6.10
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build main CSS
        run: pnpm run css-build

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@d4b9b8ff72958532804b70bbe600ad43b36d5f2e # v.0.8.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy project
        run: |
          rsync -aiv --exclude-from=exclude.txt ./ ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:/var/www/html/

      - name: Restart Nginx
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} sudo systemctl restart nginx.service
